POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "userId": "user123",
  "userName": "afreen rafi",
  "userPassword": "$eochangbin101",
  "userEmail": "afreen@gmail.com",
  "userDob": "2000-01-01",
  "userRole": "Public"
}
